### ISSUE TITLE
some examples for your playbook?

### ISSUE THREAD

**Issue by Nurlan199206** [ericsysmin/ansible-role-gcp_devel#1]
Pls you can provide some examples for your playbook or need point specific ip addressess for hosts?

i am using Ansible v2.8.2 centos 7

```
ansible-playbook --connection=local /etc/ansible/roles/ansible-role-gcp_devel/ansible-gcp.yml 
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [all] **************************************************************************************************************************************************************************************************
skipping: no hosts matched

PLAY RECAP **************************************************************************************************************************************************************************************************

```

**Comment by Nurlan199206** [comment]
or how to select google account instead hosts? i can create instances here?

![image](https://user-images.githubusercontent.com/22808731/61768431-452c9880-ae09-11e9-9e5b-984d382f855a.png)

**Comment by ericsysmin** [comment]
So, this module would use the same examples from Ansible documentation at https://docs.ansible.com/ansible/devel/modules/list_of_cloud_modules.html#google
